#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'isBalanced' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def isBalanced(s):
    st=[]
    for i in s:
        if i=='(' or i=='[' or i=='{':
            st.append(i)
        else:
             if len(st)==0:
                return 'NO'
             val=st.pop()
             if i==')' and val!='(':
                return 'NO'
             elif i==']' and val!='[':
                return 'NO'
             elif i=='}' and val!='{':
                return 'NO'
    if len(st)==0:
        return "YES"
    return 'NO'                      
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        s = input()

        result = isBalanced(s)

        fptr.write(result + '\n')

    fptr.close()
