#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#
def DigitSum(num):
    if num < 10:
        return num
    s = 0
    while num != 0:
        s += (num%10)
        num = num//10
    return DigitSum(s)
             
def superDigit(n, k):
    s = 0
    for ch in n:
        s += (ord(ch) - 48)
    return DigitSum(s * k)    
    
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()
