#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'sockMerchant' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY ar
#

def sockMerchant(n, ar):
    d=dict()
    for i in ar:
        if i not in d:
            d[i]=1
        else:
            d[i]+=1
    c=0
    for i in d:
        c=c+d[i]//2
    return c                
    
    
    c=0
    ar.sort()
    i=0
    while i<len(ar)-1:
        if ar[i]==ar[i+1]:
            c+=1
            i+=2
        else:
            i+=1
    return c            
        
         
              
                    
        
    # Write your code here
    
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
