#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'powerSum' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER X
#  2. INTEGER N
#

def Power(X,N,V=1):
    val = V**N
    if val > X:
        return 0
    if val == X:
        return 1
    return Power(X-val,N,V+1) + Power(X,N,V+1)        
def powerSum(X, N):
    return Power(X,N,1)
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    X = int(input().strip())

    N = int(input().strip())

    result = powerSum(X, N)

    fptr.write(str(result) + '\n')

    fptr.close()
